apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: access-kubeflow
  namespace: kubeflow
rules:
- apiGroups: ["", "kubeflow.org"]
  resources: ["pods", "pods/log", "experiments", "persistentvolumeclaims"]
  verbs: ["create", "delete", "update", "patch", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeflow-access-role
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-kubeflow
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: test