apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: koock
  labels:
    controller-tools.k8s.io: "1.0"
  name: mnist-katib-bayesian
spec:
  parallelTrialCount: 2
  maxTrialCount: 40
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
      - loss
      - Validation-loss
  algorithm:
    algorithmName: bayesianoptimization
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: kubeflow-registry.default.svc.cluster.local:30000/katib-job:E48DA359
                  command:
                  - "python"
                  - "/app/mnist-katib-bayesian.py"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: --dropout_rate
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.9"
    - name: --layer
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "10"        
    - name: --epoch
      parameterType: int
      feasibleSpace:
        min: "5"
        max: "15"             
    - name: --act
      parameterType: categorical
      feasibleSpace:
        list: # relu, sigmoid, softmax, tanh
        - "relu"
        - "sigmoid" 
        - "softmax"         
        - "tanh"