apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeflow-pvc
  namespace: kubeflow
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi