apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: access-instio-ingress
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-service-access-role
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-instio-ingress
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: koock